-- 회원  =====================================================================
DROP TABLE MEMBER_BOOKS;
CREATE TABLE MEMBER_BOOKS (
    MBNUM VARCHAR2(20) PRIMARY KEY 
   ,MBNAME VARCHAR2(30) 
   ,MBID VARCHAR2(20)
   ,MBPW VARCHAR2(20)
   ,MBTEL VARCHAR2(300)
   ,MBADDR VARCHAR2(200) NOT NULL
   ,DELETEYN VARCHAR2(1) NOT NULL
   ,INSERTDATE DATE
);


-- 오라클 시퀀스 
DROP SEQUENCE MEMBER_BOOKS_SEQ;
CREATE SEQUENCE MEMBER_BOOKS_SEQ
INCREMENT BY 1
START WITH 0    -- 맨처음 시작을 1 부터 하려고 
MINVALUE 0     
NOCACHE         -- 캐시를 사용할지 여부 
NOORDER;        -- 요청한 순서대로 값을 생성할지 여부

SELECT * FROM MEMBER_BOOKS ORDER BY 1;
DELETE FROM MEMBER_BOOKS;
COMMIT;

   
-- 게시판 =====================================================================
DROP TABLE BOARD_BOOKS;
CREATE TABLE BOARD_BOOKS(
	BBNUM VARCHAR2(20)		PRIMARY KEY 
   ,BBSUBJECT VARCHAR2(200)	NOT NULL
   ,BBNAME VARCHAR2(100)    NOT NULL
   ,BBCONTENT VARCHAR2(2000)
   ,BBPW VARCHAR2(300)
   ,DELETEYN VARCHAR2(1)	NOT NULL
   ,INSERTDATE DATE
   ,UPDATEDATE DATE 
);

-- 조회수 컬럼 추가 
ALTER TABLE BOARD_BOOKS ADD(BHIT NUMBER DEFAULT 0);
COMMIT;

SELECT * FROM BOARD_BOOKS ORDER BY 1 ASC ;


-- 댓글 =====================================================================
DROP TABLE RBOARD_BOOKS;
CREATE TABLE RBOARD_BOOKS (
    RBNUM VARCHAR2(20) PRIMARY KEY 
   ,BBNUM VARCHAR2(20) 
   ,RBNAME VARCHAR2(100)
   ,RBCONTENT VARCHAR2(300)    
   ,DELETEYN VARCHAR2(1)    NOT NULL
   ,INSERTDATE DATE 
   ,CONSTRAINT FK_BNUM FOREIGN KEY (BBNUM)REFERENCES BOARD_BOOKS (BBNUM)
);

SELECT * FROM RBOARD_BOOKS;

-- 상품 =====================================================================
DROP TABLE PRODUCT_BOOKS;
CREATE TABLE PRODUCT_BOOKS(
	PBNUM VARCHAR2(20) PRIMARY KEY
   ,PBNAME VARCHAR2(20) NOT NULL
   ,PBGENRE VARCHAR2(200)
   ,PBCOMPANY VARCHAR2(200)
   ,PBFILE VARCHAR2(200)
   ,PBCNT NUMBER        NOT NULL
   ,PBPRICE NUMBER      NOT NULL
   ,PBDESC VARCHAR2(2000)
   ,UPDATEDATE DATE
   ,DELETEYN VARCHAR2(1)    NOT NULL
   ,INSERTDATE DATE
);

SELECT * FROM PRODUCT_BOOKS;

-- 카트 =====================================================================
DROP TABLE CART_BOOKS;
CREATE TABLE CART_BOOKS(
    CBNUM VARCHAR2(20) PRIMARY KEY
   ,PBNUM VARCHAR2(20)
   ,PBNAME VARCHAR2(200)
   ,PBFILE VARCHAR2(200)
   ,PBCNT NUMBER   
   ,PBPRICE NUMBER
   ,PBPRICESUM NUMBER   
   ,DELETEYN VARCHAR2(1)    NOT NULL
   ,INSERTDATE DATE
   ,UPDATEDATE DATE
   ,CONSTRAINT FK_PBNUM FOREIGN KEY (PBNUM)REFERENCES PRODUCT_BOOKS (PBNUM)
);


-- 주문 =====================================================================
DROP TABLE ORDER_BOOKS;
CREATE TABLE ORDER_BOOKS (   
     OBNUM VARCHAR2(20) PRIMARY KEY -- 상품주문번호 
    ,PBNUM VARCHAR2(20) 
    ,PBNAME VARCHAR2(20)
    ,PBCNT VARCHAR2(200)    NOT NULL    
    ,PBPRICE NUMBER   
    ,PBPRICESUM NUMBER
    ,CBNUM VARCHAR2(20)
    ,CBMID VARCHAR2(20) 
    ,CBMNAME VARCHAR2(20) 
    ,CBMHP VARCHAR2(100)
    ,CBMEMAIL VARCHAR2(16)  
    ,OODERIVARY VARCHAR2(200) 
    ,OOZONE VARCHAR2(10) -- 배송방법 01, 02, 03
    ,OOROAD VARCHAR2(6)
    ,OOROAD2 VARCHAR2(200)
    ,OOJIBUN VARCHAR2(200) 
    ,DELETEYN VARCHAR2(1)   NOT NULL
    ,INSERTDATE DATE
    ,UPDATEDATE DATE   
    ,CONSTRAINT FK_OB_PBNUM FOREIGN KEY (PBNUM)REFERENCES PRODUCT_BOOKS (PBNUM)
    ,CONSTRAINT FK_CBNUM FOREIGN KEY (CBNUM)REFERENCES CART_BOOKS (CBNUM)
);

SELECT * FROM ORDER_BOOKS;

-- 카드결제 
-- DROP TABLE KOSMO_CARD;
-- CREATE TABLE KOSMO_CARD ();

--ROW_NUMBER : 중복순위 없이 유일값. (1,2,3,4)


---------------------------------------------------------------------
--게시판 페이징
DROP TABLE BOARD_PAGING_BOOKS;
CREATE TABLE BOARD_PAGING_BOOKS(
	BPNUM		NUMBER(20)			PRIMARY KEY,
	BPTITLE		VARCHAR2(50)		NOT NULL,
	BPNAME		VARCHAR2(20)		NOT NULL,
	BPAREA		VARCHAR2(2000)		NOT NULL,
	BPPASS		VARCHAR2(20)		NULL,
	BPWRITEDAY	DATE				DEFAULT SYSDATE,
	BPHITS		NUMBER(8)			NULL
);    

DROP SEQUENCE B_SEQ;
CREATE SEQUENCE B_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE FAQ_BOOKS (
    FBNUM       VARCHAR2(20) PRIMARY KEY,
    BPCATEGORY  VARCHAR2(50),
    FBTITLE     VARCHAR2(20)
);